/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import restaurante.Factura;
import restaurante.Restaurante;

/**
 *
 * @author DELL
 */
public class Facturas extends javax.swing.JFrame {

    /**
     * Creates new form Facturas
     */
    
    private Restaurante restaurante ;
    private ArrayList<Factura> lfacturas ;
    private double dinero ;
    private int item ;
    
    public Facturas(Restaurante restaurante, double dinero) {
        getContentPane().setBackground(Color.PINK);
        this.restaurante = restaurante ;
        this.lfacturas = restaurante.getAlmacen().getFacturas() ;
        this.dinero = dinero ;
        initComponents();
    }
    
    public void actualizarTabla(){
        String matrix[][] = new String[lfacturas.size()][4] ;
        for( int i = 0 ; i < lfacturas.size() ; i++){
            int j = i+1 ;
            matrix[i][0] = Integer.toString(j) ;
            matrix[i][1] = lfacturas.get(i).getFechaVencimiento().toString() ;
            matrix[i][2] = Double.toString(lfacturas.get(i).getValor()) ;
            matrix[i][3] = lfacturas.get(i).getProveedor().getNombre();
        }
        
        TablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            matrix,
            new String [] {
                "# item", "Fecha Vencimiento", "Valor", "Proveedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class
            };

        });
    }
    public void mostrarDinero(){
        String matrix[][] = new String[1][1] ;
        
        matrix[0][0] = Double.toString(restaurante.getAlmacen().getDineroDisp()) ;
        
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
            matrix,
            new String [] {
                ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFacturas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonColoredAction6 = new org.edisoncor.gui.button.ButtonColoredAction();
        jLabel4 = new javax.swing.JLabel();
        facturatxt = new javax.swing.JTextField();
        buttonColoredAction7 = new org.edisoncor.gui.button.ButtonColoredAction();
        buttonColoredAction8 = new org.edisoncor.gui.button.ButtonColoredAction();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "# item", "Fecha Vencimiento", "Valor", "Proveedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaFacturas.setRowHeight(20);
        TablaFacturas.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TablaFacturasInputMethodTextChanged(evt);
            }
        });
        TablaFacturas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TablaFacturasPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(TablaFacturas);

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 36)); // NOI18N
        jLabel1.setText("Pago de Facturas");

        buttonColoredAction6.setBackground(new java.awt.Color(204, 255, 255));
        buttonColoredAction6.setForeground(new java.awt.Color(0, 0, 0));
        buttonColoredAction6.setText("< Volver");
        buttonColoredAction6.setColorDeSombra(new java.awt.Color(204, 255, 255));
        buttonColoredAction6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction6ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        jLabel4.setText("Factura a pagar");

        facturatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturatxtActionPerformed(evt);
            }
        });

        buttonColoredAction7.setBackground(new java.awt.Color(204, 255, 255));
        buttonColoredAction7.setForeground(new java.awt.Color(0, 0, 0));
        buttonColoredAction7.setText("Pagar Factura");
        buttonColoredAction7.setColorDeSombra(new java.awt.Color(204, 255, 255));
        buttonColoredAction7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction7ActionPerformed(evt);
            }
        });

        buttonColoredAction8.setBackground(new java.awt.Color(204, 255, 255));
        buttonColoredAction8.setForeground(new java.awt.Color(0, 0, 0));
        buttonColoredAction8.setText("Actualizar tabla");
        buttonColoredAction8.setColorDeSombra(new java.awt.Color(204, 255, 255));
        buttonColoredAction8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction8ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Dinero disponible");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonColoredAction6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(buttonColoredAction7, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(buttonColoredAction8, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(facturatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap(51, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(buttonColoredAction8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(facturatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(buttonColoredAction7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(buttonColoredAction6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaFacturasInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TablaFacturasInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaFacturasInputMethodTextChanged

    private void TablaFacturasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TablaFacturasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaFacturasPropertyChange

    private void buttonColoredAction6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction6ActionPerformed
        // TODO add your handling code here:
        this.hide();
        try {
            new MateriaPrima(restaurante).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonColoredAction6ActionPerformed

    private void facturatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturatxtActionPerformed

    }//GEN-LAST:event_facturatxtActionPerformed

    private void buttonColoredAction7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction7ActionPerformed
        // TODO add your handling code here:
        try{

            this.item = Integer.parseInt(facturatxt.getText()) ;
            if(dinero < lfacturas.get(item-1).getValor()){
                JOptionPane.showMessageDialog(null, "No hay dinero suficiente");
            }
            else{
                dinero -= lfacturas.get(item-1).getValor() ;
                lfacturas.remove(item-1) ;
            }

        }
        catch( NumberFormatException ex ){
            System.out.println("NumberFormatException");
        }
        catch( ArrayIndexOutOfBoundsException ex){
            System.out.println("ArrayIndexOutOfBoundsException");
        }
        catch(NullPointerException ex){
            System.out.println("NullPointerException");
        }

        //System.out.println(this.item + " " + this.cantidad);
        //System.out.println(matrix[this.item][2]);
        actualizarTabla();
    }//GEN-LAST:event_buttonColoredAction7ActionPerformed

    private void buttonColoredAction8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction8ActionPerformed
        // TODO add your handling code here:
        actualizarTabla();
    }//GEN-LAST:event_buttonColoredAction8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mostrarDinero();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaFacturas;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction6;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction7;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction8;
    private javax.swing.JTextField facturatxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
