/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import restaurante.Categoria;
import restaurante.Restaurante;

/**
 *
 * @author User
 */
public class MateriaPrima extends javax.swing.JFrame {
 
    /**
     * Creates new form MateriaPrima
     */
	private Restaurante restaurante;
        private double dinero ;
        int posx = 100 ;
        int posy = 500 ;
        int xfinal = 15 ;
        int yfinal = 500 ;
        int xini = 15 ;
        int yini = 500 ;
        //BufferedImage robot ;
        
        public MateriaPrima(Restaurante restaurante) throws IOException {
        getContentPane().setBackground(Color.PINK);
        initComponents();
        this.restaurante = restaurante;
        this.dinero = 0.0 ;
        this.setResizable(false);
        //robot = ImageIO.read(new File("robotsito.png"));
    }
        
    public void moverRobotcaja() throws InterruptedException{
        for( int i = 0 ; i < restaurante.getEntradaProductos().size() ; i++){
            if( restaurante.getEntradaProductos().get(i).isCongelado() || restaurante.getEntradaProductos().get(i).isRefrigerado()){
                robotsito.move(470, 400);
                Thread.sleep(1000);
                robotsito.move(470, 200);
            }
            if( restaurante.getEntradaProductos().get(i).isTempAmbiente()){
                robotsito.move(230, 400);
                Thread.sleep(1000);
                robotsito.move(230, 200);
            }
            
        }
        
        
    }
    
    public void moverRobotini(){
            try {
                Thread.sleep(1500);
            } catch (InterruptedException ex) {
                Logger.getLogger(MateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
            }
        robotsito.move(100, 400);
    }
    
    public void paint(Graphics g){
        super.paint(g);
        //g.drawImage(robot, posx, posy, null) ;
        //g.dispose();
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void mostrarProveedores(){
        String matrix[][] = new String[restaurante.getProveedores().size()][3] ;
        
        for( int i = 0 ; i < restaurante.getProveedores().size() ; i++){
            matrix[i][0] = restaurante.getProveedores().get(i).nombre ;
            matrix[i][1] = Integer.toString(restaurante.getProveedores().get(i).getNit()) ;
            matrix[i][2] = Integer.toString(restaurante.getProveedores().get(i).getTelefono()) ;
        }
        
        TablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            matrix,
            new String [] {
                "Nombre", "NIT", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

        });
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        move1 = new com.sun.animation.effects.Move();
        buttonAqua1 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAeroRight1 = new org.edisoncor.gui.button.ButtonAeroRight();
        buttonAeroRound1 = new org.edisoncor.gui.button.ButtonAeroRound();
        jScrollBar1 = new javax.swing.JScrollBar();
        panelImage20 = new org.edisoncor.gui.panel.PanelImage();
        move2 = new com.sun.animation.effects.Move();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProveedores = new javax.swing.JTable();
        buttonColoredAction1 = new org.edisoncor.gui.button.ButtonColoredAction();
        buttonColoredAction2 = new org.edisoncor.gui.button.ButtonColoredAction();
        buttonColoredAction5 = new org.edisoncor.gui.button.ButtonColoredAction();
        buttonColoredAction9 = new org.edisoncor.gui.button.ButtonColoredAction();
        panel2 = new org.edisoncor.gui.panel.Panel();
        jLabel2 = new javax.swing.JLabel();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        panelImage6 = new org.edisoncor.gui.panel.PanelImage();
        panelImage7 = new org.edisoncor.gui.panel.PanelImage();
        panelImage10 = new org.edisoncor.gui.panel.PanelImage();
        panelImage11 = new org.edisoncor.gui.panel.PanelImage();
        panelImage12 = new org.edisoncor.gui.panel.PanelImage();
        panelImage19 = new org.edisoncor.gui.panel.PanelImage();
        panelImage21 = new org.edisoncor.gui.panel.PanelImage();
        panelImage22 = new org.edisoncor.gui.panel.PanelImage();
        panelImage23 = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        panelImage13 = new org.edisoncor.gui.panel.PanelImage();
        panelImage14 = new org.edisoncor.gui.panel.PanelImage();
        panelImage16 = new org.edisoncor.gui.panel.PanelImage();
        panelImage17 = new org.edisoncor.gui.panel.PanelImage();
        panelImage18 = new org.edisoncor.gui.panel.PanelImage();
        panelImage27 = new org.edisoncor.gui.panel.PanelImage();
        panelImage28 = new org.edisoncor.gui.panel.PanelImage();
        robotsito = new org.edisoncor.gui.panel.PanelImage();
        buttonColoredAction6 = new org.edisoncor.gui.button.ButtonColoredAction();
        buttonColoredAction10 = new org.edisoncor.gui.button.ButtonColoredAction();
        dinerotxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        moverRobotbtn = new org.edisoncor.gui.button.ButtonColoredAction();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        buttonAqua1.setText("buttonAqua1");

        buttonAeroRight1.setText("buttonAeroRight1");

        buttonAeroRound1.setText("buttonAeroRound1");

        panelImage20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kisspng-refrigerator-computer-icons-home-appliance-freezer-5cc151013fa413.4745125515561730572607.png"))); // NOI18N

        javax.swing.GroupLayout panelImage20Layout = new javax.swing.GroupLayout(panelImage20);
        panelImage20.setLayout(panelImage20Layout);
        panelImage20Layout.setHorizontalGroup(
            panelImage20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage20Layout.setVerticalGroup(
            panelImage20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 36)); // NOI18N
        jLabel1.setText("Bodega Materia Prima");

        TablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "NIT", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaProveedores.setRowHeight(25);
        jScrollPane1.setViewportView(TablaProveedores);

        buttonColoredAction1.setBackground(new java.awt.Color(204, 255, 255));
        buttonColoredAction1.setForeground(new java.awt.Color(0, 0, 0));
        buttonColoredAction1.setText("Ingresar pedido de productos");
        buttonColoredAction1.setColorDeSombra(new java.awt.Color(204, 255, 255));
        buttonColoredAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction1ActionPerformed(evt);
            }
        });

        buttonColoredAction2.setBackground(new java.awt.Color(204, 255, 255));
        buttonColoredAction2.setForeground(new java.awt.Color(0, 0, 0));
        buttonColoredAction2.setText("Salida de productos");
        buttonColoredAction2.setColorDeSombra(new java.awt.Color(204, 255, 255));
        buttonColoredAction2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction2ActionPerformed(evt);
            }
        });

        buttonColoredAction5.setBackground(new java.awt.Color(204, 255, 255));
        buttonColoredAction5.setForeground(new java.awt.Color(0, 0, 0));
        buttonColoredAction5.setText("Consultas");
        buttonColoredAction5.setColorDeSombra(new java.awt.Color(204, 255, 255));
        buttonColoredAction5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction5ActionPerformed(evt);
            }
        });

        buttonColoredAction9.setBackground(new java.awt.Color(204, 255, 255));
        buttonColoredAction9.setForeground(new java.awt.Color(0, 0, 0));
        buttonColoredAction9.setText("Proveedores");
        buttonColoredAction9.setColorDeSombra(new java.awt.Color(204, 255, 255));
        buttonColoredAction9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction9ActionPerformed(evt);
            }
        });

        panel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        jLabel2.setText("Cuarto frío");

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kisspng-refrigerator-computer-icons-home-appliance-freezer-5cc151013fa413.4745125515561730572607.png"))); // NOI18N

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kisspng-refrigerator-computer-icons-home-appliance-freezer-5cc151013fa413.4745125515561730572607.png"))); // NOI18N

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage4Layout.setVerticalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kisspng-refrigerator-computer-icons-home-appliance-freezer-5cc151013fa413.4745125515561730572607.png"))); // NOI18N

        javax.swing.GroupLayout panelImage5Layout = new javax.swing.GroupLayout(panelImage5);
        panelImage5.setLayout(panelImage5Layout);
        panelImage5Layout.setHorizontalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage5Layout.setVerticalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kisspng-refrigerator-computer-icons-home-appliance-freezer-5cc151013fa413.4745125515561730572607.png"))); // NOI18N

        javax.swing.GroupLayout panelImage6Layout = new javax.swing.GroupLayout(panelImage6);
        panelImage6.setLayout(panelImage6Layout);
        panelImage6Layout.setHorizontalGroup(
            panelImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImage6Layout.setVerticalGroup(
            panelImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kisspng-refrigerator-computer-icons-home-appliance-freezer-5cc151013fa413.4745125515561730572607.png"))); // NOI18N

        javax.swing.GroupLayout panelImage7Layout = new javax.swing.GroupLayout(panelImage7);
        panelImage7.setLayout(panelImage7Layout);
        panelImage7Layout.setHorizontalGroup(
            panelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage7Layout.setVerticalGroup(
            panelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kisspng-refrigerator-computer-icons-home-appliance-freezer-5cc151013fa413.4745125515561730572607.png"))); // NOI18N

        javax.swing.GroupLayout panelImage10Layout = new javax.swing.GroupLayout(panelImage10);
        panelImage10.setLayout(panelImage10Layout);
        panelImage10Layout.setHorizontalGroup(
            panelImage10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImage10Layout.setVerticalGroup(
            panelImage10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kisspng-refrigerator-computer-icons-home-appliance-freezer-5cc151013fa413.4745125515561730572607.png"))); // NOI18N

        javax.swing.GroupLayout panelImage11Layout = new javax.swing.GroupLayout(panelImage11);
        panelImage11.setLayout(panelImage11Layout);
        panelImage11Layout.setHorizontalGroup(
            panelImage11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage11Layout.setVerticalGroup(
            panelImage11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kisspng-refrigerator-computer-icons-home-appliance-freezer-5cc151013fa413.4745125515561730572607.png"))); // NOI18N

        javax.swing.GroupLayout panelImage12Layout = new javax.swing.GroupLayout(panelImage12);
        panelImage12.setLayout(panelImage12Layout);
        panelImage12Layout.setHorizontalGroup(
            panelImage12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage12Layout.setVerticalGroup(
            panelImage12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage19Layout = new javax.swing.GroupLayout(panelImage19);
        panelImage19.setLayout(panelImage19Layout);
        panelImage19Layout.setHorizontalGroup(
            panelImage19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage19Layout.setVerticalGroup(
            panelImage19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage21Layout = new javax.swing.GroupLayout(panelImage21);
        panelImage21.setLayout(panelImage21Layout);
        panelImage21Layout.setHorizontalGroup(
            panelImage21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage21Layout.setVerticalGroup(
            panelImage21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage22Layout = new javax.swing.GroupLayout(panelImage22);
        panelImage22.setLayout(panelImage22Layout);
        panelImage22Layout.setHorizontalGroup(
            panelImage22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage22Layout.setVerticalGroup(
            panelImage22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage23Layout = new javax.swing.GroupLayout(panelImage23);
        panelImage23.setLayout(panelImage23Layout);
        panelImage23Layout.setHorizontalGroup(
            panelImage23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage23Layout.setVerticalGroup(
            panelImage23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelImage13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage13Layout = new javax.swing.GroupLayout(panelImage13);
        panelImage13.setLayout(panelImage13Layout);
        panelImage13Layout.setHorizontalGroup(
            panelImage13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage13Layout.setVerticalGroup(
            panelImage13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage14Layout = new javax.swing.GroupLayout(panelImage14);
        panelImage14.setLayout(panelImage14Layout);
        panelImage14Layout.setHorizontalGroup(
            panelImage14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage14Layout.setVerticalGroup(
            panelImage14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage16Layout = new javax.swing.GroupLayout(panelImage16);
        panelImage16.setLayout(panelImage16Layout);
        panelImage16Layout.setHorizontalGroup(
            panelImage16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage16Layout.setVerticalGroup(
            panelImage16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage17Layout = new javax.swing.GroupLayout(panelImage17);
        panelImage17.setLayout(panelImage17Layout);
        panelImage17Layout.setHorizontalGroup(
            panelImage17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage17Layout.setVerticalGroup(
            panelImage17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage18Layout = new javax.swing.GroupLayout(panelImage18);
        panelImage18.setLayout(panelImage18Layout);
        panelImage18Layout.setHorizontalGroup(
            panelImage18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage18Layout.setVerticalGroup(
            panelImage18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage27Layout = new javax.swing.GroupLayout(panelImage27);
        panelImage27.setLayout(panelImage27Layout);
        panelImage27Layout.setHorizontalGroup(
            panelImage27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage27Layout.setVerticalGroup(
            panelImage27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelImage28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caja (2).png"))); // NOI18N

        javax.swing.GroupLayout panelImage28Layout = new javax.swing.GroupLayout(panelImage28);
        panelImage28.setLayout(panelImage28Layout);
        panelImage28Layout.setHorizontalGroup(
            panelImage28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        panelImage28Layout.setVerticalGroup(
            panelImage28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        robotsito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Robotsito.png"))); // NOI18N
        robotsito.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                robotsitoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        robotsito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robotsitoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout robotsitoLayout = new javax.swing.GroupLayout(robotsito);
        robotsito.setLayout(robotsitoLayout);
        robotsitoLayout.setHorizontalGroup(
            robotsitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        robotsitoLayout.setVerticalGroup(
            robotsitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(43, 43, 43))
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addComponent(robotsito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelImage28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelImage14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelImage13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelImage18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelImage27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelImage17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelImage16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelImage22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelImage21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelImage7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelImage11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(panelImage23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelImage19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)))
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panelImage10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelImage6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelImage12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImage16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImage4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImage5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImage23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImage19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImage13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImage17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImage6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImage14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImage18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImage22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImage7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImage10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImage12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImage11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelImage28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelImage27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelImage21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(robotsito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        buttonColoredAction6.setBackground(new java.awt.Color(204, 255, 255));
        buttonColoredAction6.setForeground(new java.awt.Color(0, 0, 0));
        buttonColoredAction6.setText("< Volver");
        buttonColoredAction6.setColorDeSombra(new java.awt.Color(204, 255, 255));
        buttonColoredAction6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction6ActionPerformed(evt);
            }
        });

        buttonColoredAction10.setBackground(new java.awt.Color(204, 255, 255));
        buttonColoredAction10.setForeground(new java.awt.Color(0, 0, 0));
        buttonColoredAction10.setText("Pagar Facturas");
        buttonColoredAction10.setColorDeSombra(new java.awt.Color(204, 255, 255));
        buttonColoredAction10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction10ActionPerformed(evt);
            }
        });

        dinerotxt.setText("Dinero en caja");

        jButton1.setText("Actualizar Dinero en Caja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        moverRobotbtn.setBackground(new java.awt.Color(204, 255, 255));
        moverRobotbtn.setForeground(new java.awt.Color(0, 0, 0));
        moverRobotbtn.setText("Mover robot");
        moverRobotbtn.setColorDeSombra(new java.awt.Color(204, 255, 255));
        moverRobotbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moverRobotbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonColoredAction2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonColoredAction1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(buttonColoredAction5, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(buttonColoredAction10, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(buttonColoredAction9, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(dinerotxt)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(moverRobotbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonColoredAction6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonColoredAction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonColoredAction2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonColoredAction5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonColoredAction10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonColoredAction9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dinerotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(moverRobotbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonColoredAction6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonColoredAction6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction6ActionPerformed
        // TODO add your handling code here:
        this.hide();
        new Sistema(restaurante).setVisible(true);
    }//GEN-LAST:event_buttonColoredAction6ActionPerformed

    private void buttonColoredAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        new IngresoPedido(restaurante).setVisible(true);
    }//GEN-LAST:event_buttonColoredAction1ActionPerformed

    private void buttonColoredAction5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction5ActionPerformed
        // TODO add your handling code here:
        this.hide();
        new InventarioMatPrima(restaurante).setVisible(true);
    }//GEN-LAST:event_buttonColoredAction5ActionPerformed

    private void buttonColoredAction9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction9ActionPerformed
        // TODO add your handling code here:
        mostrarProveedores() ;
    }//GEN-LAST:event_buttonColoredAction9ActionPerformed

    private void buttonColoredAction2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction2ActionPerformed
        // TODO add your handling code here:
        this.hide();
        new SalidaMatPrima(restaurante).setVisible(true);
    }//GEN-LAST:event_buttonColoredAction2ActionPerformed

    private void buttonColoredAction10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction10ActionPerformed
        // TODO add your handling code here:
        this.hide();
        new Facturas(restaurante, dinero).setVisible(true);
    }//GEN-LAST:event_buttonColoredAction10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        this.dinero = Double.parseDouble(dinerotxt.getText()) ;
        }
        catch(NumberFormatException ex){
            System.out.println("NumberFormatException");
        }
        System.out.println(this.dinero);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void robotsitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robotsitoMouseClicked
        // TODO add your handling code here:
        System.out.println("Hola mundo");
    }//GEN-LAST:event_robotsitoMouseClicked

    private void robotsitoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_robotsitoAncestorAdded

    }//GEN-LAST:event_robotsitoAncestorAdded

    private void moverRobotbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moverRobotbtnActionPerformed
            try {
                // TODO add your handling code here:
                //moverRobotcaja() ;
                if(restaurante.getAlmacen().isMoverRobotentrada() || restaurante.getAlmacen().isMoverRobotsalida()){
                    moverRobotcaja() ;
                    moverRobotini();
                }
                else JOptionPane.showMessageDialog(null, "No hay acciones a realizar");
            } catch (InterruptedException ex) {
                Logger.getLogger(MateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_moverRobotbtnActionPerformed

    /**s
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//       
//        
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MateriaPrima().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProveedores;
    private org.edisoncor.gui.button.ButtonAeroRight buttonAeroRight1;
    private org.edisoncor.gui.button.ButtonAeroRound buttonAeroRound1;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua1;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction1;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction10;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction2;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction5;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction6;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction9;
    private javax.swing.JTextField dinerotxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.sun.animation.effects.Move move1;
    private com.sun.animation.effects.Move move2;
    private org.edisoncor.gui.button.ButtonColoredAction moverRobotbtn;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.PanelImage panelImage10;
    private org.edisoncor.gui.panel.PanelImage panelImage11;
    private org.edisoncor.gui.panel.PanelImage panelImage12;
    private org.edisoncor.gui.panel.PanelImage panelImage13;
    private org.edisoncor.gui.panel.PanelImage panelImage14;
    private org.edisoncor.gui.panel.PanelImage panelImage16;
    private org.edisoncor.gui.panel.PanelImage panelImage17;
    private org.edisoncor.gui.panel.PanelImage panelImage18;
    private org.edisoncor.gui.panel.PanelImage panelImage19;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage20;
    private org.edisoncor.gui.panel.PanelImage panelImage21;
    private org.edisoncor.gui.panel.PanelImage panelImage22;
    private org.edisoncor.gui.panel.PanelImage panelImage23;
    private org.edisoncor.gui.panel.PanelImage panelImage27;
    private org.edisoncor.gui.panel.PanelImage panelImage28;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private org.edisoncor.gui.panel.PanelImage panelImage6;
    private org.edisoncor.gui.panel.PanelImage panelImage7;
    private org.edisoncor.gui.panel.PanelImage robotsito;
    // End of variables declaration//GEN-END:variables
}
