/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import restaurante.Categoria;
import restaurante.Producto;
import restaurante.Restaurante;

/**
 *
 * @author DELL
 */
public class SalidaMatPrima extends javax.swing.JFrame {
    private int item ;
    private int cantidad ;
    private Restaurante restaurante ;
    private ArrayList<Producto> salida ;
    private ArrayList<Producto> productos ;
    private ArrayList<Integer> cantidades ;
    /**
     * Creates new form SalidaMatPrima
     * @param restaurante
     */
    public SalidaMatPrima(Restaurante restaurante) {
        getContentPane().setBackground(Color.PINK);
        this.restaurante = restaurante ;
        this.salida = new ArrayList<>() ;
        this.cantidades = new ArrayList<>() ;
        this.productos = restaurante.getAlmacen().getInventario() ;
        initComponents();
    }
    public void actualizarTabla(){
        //Collections.sort(productos);
        String matrix[][] = new String[restaurante.getAlmacen().getInventario().size()][3] ;
        for( int i = 0 ; i < restaurante.getAlmacen().getInventario().size() ; i++){
            int j = i+1 ;
            matrix[i][0] = Integer.toString(j) ;
            matrix[i][1] = restaurante.getAlmacen().getInventario().get(i).nombre ;
            matrix[i][2] = Integer.toString(restaurante.getAlmacen().getInventario().get(i).cantidad) ;
        }
        
        TablaSalida.setModel(new javax.swing.table.DefaultTableModel(
            matrix,
            new String [] {
                "# item", "Nombre", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSalida = new javax.swing.JTable();
        buttonColoredAction6 = new org.edisoncor.gui.button.ButtonColoredAction();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        itemtxt = new javax.swing.JTextField();
        cantidadtxt = new javax.swing.JTextField();
        buttonColoredAction7 = new org.edisoncor.gui.button.ButtonColoredAction();
        buttonColoredAction8 = new org.edisoncor.gui.button.ButtonColoredAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 36)); // NOI18N
        jLabel1.setText("Salida de producto");

        TablaSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "# item", "Nombre", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaSalida.setRowHeight(20);
        TablaSalida.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TablaSalidaInputMethodTextChanged(evt);
            }
        });
        TablaSalida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TablaSalidaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(TablaSalida);

        buttonColoredAction6.setBackground(new java.awt.Color(204, 255, 255));
        buttonColoredAction6.setForeground(new java.awt.Color(0, 0, 0));
        buttonColoredAction6.setText("< Volver");
        buttonColoredAction6.setColorDeSombra(new java.awt.Color(204, 255, 255));
        buttonColoredAction6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction6ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        jLabel3.setText("# item");

        jLabel4.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        jLabel4.setText("Cantidad");

        itemtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemtxtActionPerformed(evt);
            }
        });

        cantidadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadtxtActionPerformed(evt);
            }
        });

        buttonColoredAction7.setBackground(new java.awt.Color(204, 255, 255));
        buttonColoredAction7.setForeground(new java.awt.Color(0, 0, 0));
        buttonColoredAction7.setText("Actualizar Tabla");
        buttonColoredAction7.setColorDeSombra(new java.awt.Color(204, 255, 255));
        buttonColoredAction7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction7ActionPerformed(evt);
            }
        });

        buttonColoredAction8.setBackground(new java.awt.Color(204, 255, 255));
        buttonColoredAction8.setForeground(new java.awt.Color(0, 0, 0));
        buttonColoredAction8.setText("Confirmar Descarga");
        buttonColoredAction8.setColorDeSombra(new java.awt.Color(204, 255, 255));
        buttonColoredAction8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cantidadtxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(itemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonColoredAction7, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonColoredAction8, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(buttonColoredAction6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(itemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(cantidadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(buttonColoredAction7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonColoredAction8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(buttonColoredAction6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaSalidaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TablaSalidaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaSalidaInputMethodTextChanged

    private void TablaSalidaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TablaSalidaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaSalidaPropertyChange

    private void buttonColoredAction6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction6ActionPerformed
        // TODO add your handling code here:
        this.hide();
        try {
            new MateriaPrima(restaurante).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(SalidaMatPrima.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonColoredAction6ActionPerformed

    private void itemtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemtxtActionPerformed
        // TODO add your handling code here:
        this.item = Integer.parseInt(itemtxt.getText()) ;
        //System.out.println("item " + this.item);
    }//GEN-LAST:event_itemtxtActionPerformed

    private void cantidadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadtxtActionPerformed
        // TODO add your handling code here:
        this.cantidad = Integer.parseInt(cantidadtxt.getText()) ;
        //System.out.println("cantidad " + this.cantidad);
    }//GEN-LAST:event_cantidadtxtActionPerformed

    private void buttonColoredAction7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction7ActionPerformed
        // TODO add your handling code here:
        try{

            this.item = Integer.parseInt(itemtxt.getText())-1 ;
            this.cantidad = Integer.parseInt(cantidadtxt.getText()) ;
            if(restaurante.getAlmacen().getInventario().get(item).cantidad - this.cantidad < 0 ){
                JOptionPane.showMessageDialog(null, "No hay productos suficientes");
            }
            else{
                restaurante.getAlmacen().getInventario().get(item).cantidad -= this.cantidad ;
                salida.add(restaurante.getAlmacen().getInventario().get(item)) ;
                cantidades.add(this.cantidad) ;
            }

        }
        catch( NumberFormatException ex ){
            System.out.println("NumberFormatException");
        }
        catch( ArrayIndexOutOfBoundsException ex){
            System.out.println("ArrayIndexOutOfBoundsException");
        }
        catch(NullPointerException ex){
            System.out.println("NullPointerException");
        }

        //System.out.println(this.item + " " + this.cantidad);
        //System.out.println(matrix[this.item][2]);
        actualizarTabla();
    }//GEN-LAST:event_buttonColoredAction7ActionPerformed

    private void buttonColoredAction8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction8ActionPerformed
        // TODO add your handling code here:
        restaurante.setCambioDeBodega(salida);
        for(int i = 0 ; i < restaurante.getCambioDeBodega().size() ; i++ ){
            for( int j = 0 ; j < restaurante.getProduccion().getInventario().size() ; j++ ){
                if(restaurante.getCambioDeBodega().get(i).getNombre().equals(restaurante.getProduccion().getInventario().get(j).getNombre())){
                    restaurante.getProduccion().getInventario().get(j).setCantidad(cantidades.get(i) + restaurante.getProduccion().getInventario().get(j).getCantidad());
                    break ;
                }
            }
        }
        restaurante.getAlmacen().setMoverRobotsalida(true);
        this.hide();
        try {
            new MateriaPrima(restaurante).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(SalidaMatPrima.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonColoredAction8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaSalida;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction6;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction7;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction8;
    private javax.swing.JTextField cantidadtxt;
    private javax.swing.JTextField itemtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
